// Code generated by `cmd/protocols`; DO NOT EDIT.

package wayland

import "github.com/mmulet/term.everything/wayland/protocols"

func GetWlSurfaceObject(cs protocols.ClientState, id protocols.ObjectID[protocols.WlSurface]) *WlSurface {
	v := cs.GetObject(protocols.AnyObjectID(id))
	if v == nil {
		return nil
	}
	o := v.(protocols.WaylandObject[protocols.WlSurface_delegate])
	d := o.GetDelegate()
	return d.(*WlSurface)
}

func GetWlPointerObject(cs protocols.ClientState, id protocols.ObjectID[protocols.WlPointer]) *WlPointer {
	v := cs.GetObject(protocols.AnyObjectID(id))
	if v == nil {
		return nil
	}
	o := v.(protocols.WaylandObject[protocols.WlPointer_delegate])
	d := o.GetDelegate()
	return d.(*WlPointer)
}

func GetWlSubsurfaceObject(cs protocols.ClientState, id protocols.ObjectID[protocols.WlSubsurface]) *WlSubsurface {
	v := cs.GetObject(protocols.AnyObjectID(id))
	if v == nil {
		return nil
	}
	o := v.(protocols.WaylandObject[protocols.WlSubsurface_delegate])
	d := o.GetDelegate()
	return d.(*WlSubsurface)
}
