// Code generated by `cmd/protocols`; DO NOT EDIT.

package wayland

import "github.com/mmulet/term.everything/wayland/protocols"

func GetXdgPositionerObject(cs protocols.ClientState, id protocols.ObjectID[protocols.XdgPositioner]) *XdgPositioner {
	v := cs.GetObject(protocols.AnyObjectID(id))
	if v == nil {
		return nil
	}
	o := v.(protocols.WaylandObject[protocols.XdgPositioner_delegate])
	d := o.GetDelegate()
	return d.(*XdgPositioner)
}

func GetXdgSurfaceObject(cs protocols.ClientState, id protocols.ObjectID[protocols.XdgSurface]) *XdgSurface {
	v := cs.GetObject(protocols.AnyObjectID(id))
	if v == nil {
		return nil
	}
	o := v.(protocols.WaylandObject[protocols.XdgSurface_delegate])
	d := o.GetDelegate()
	return d.(*XdgSurface)
}

func GetXdgToplevelObject(cs protocols.ClientState, id protocols.ObjectID[protocols.XdgToplevel]) *XdgToplevel {
	v := cs.GetObject(protocols.AnyObjectID(id))
	if v == nil {
		return nil
	}
	o := v.(protocols.WaylandObject[protocols.XdgToplevel_delegate])
	d := o.GetDelegate()
	return d.(*XdgToplevel)
}
