// Code generated by `cmd/protocols`; DO NOT EDIT.

package protocols

import "fmt"

type ZxdgDecorationManagerV1_delegate interface {
	ZxdgDecorationManagerV1_destroy(s ClientState, object_id ObjectID[ZxdgDecorationManagerV1]) bool
	ZxdgDecorationManagerV1_get_toplevel_decoration(s ClientState, object_id ObjectID[ZxdgDecorationManagerV1], id ObjectID[ZxdgToplevelDecorationV1], toplevel ObjectID[XdgToplevel])
	OnBind(s ClientState, name AnyObjectID, interface_ string, new_id AnyObjectID, version_number uint32)
}

type ZxdgDecorationManagerV1 struct {
	Delegate ZxdgDecorationManagerV1_delegate
}

func (p *ZxdgDecorationManagerV1) GetDelegate() ZxdgDecorationManagerV1_delegate {
	return p.Delegate
}
func (p *ZxdgDecorationManagerV1) GetBindable() OnBindable {
	return p.Delegate
}

func (p *ZxdgDecorationManagerV1) OnRequest(s FileDescriptorClaimClientState, message Message) {
	_data_in_offset__ := 0
	_ = _data_in_offset__
	d := p.Delegate
	switch message.Opcode {
	case 0:
		{

			if DebugRequests {
				fmt.Print("ZxdgDecorationManagerV1@", message.ObjectID, ".destroy(")
				fmt.Println(")")
			}

			autoRemove := d.ZxdgDecorationManagerV1_destroy(s, ObjectID[ZxdgDecorationManagerV1](message.ObjectID))
			if autoRemove {
				s.RemoveObject(message.ObjectID)
			}
			break
		}

	case 1:
		{

			idVal := uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24
			id := ObjectID[ZxdgToplevelDecorationV1](idVal)
			_data_in_offset__ += 4

			toplevel := ObjectID[XdgToplevel](uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			if DebugRequests {
				fmt.Print("ZxdgDecorationManagerV1@", message.ObjectID, ".get_toplevel_decoration(")
				fmt.Println("id: ", id, ", ", "toplevel: ", toplevel, ")")
			}

			d.ZxdgDecorationManagerV1_get_toplevel_decoration(s, ObjectID[ZxdgDecorationManagerV1](message.ObjectID), id, toplevel)
			break
		}

	default:
		fmt.Println("Unknown opcode on ZxdgDecorationManagerV1", message.Opcode)
	}
}

type ZxdgToplevelDecorationV1_delegate interface {
	ZxdgToplevelDecorationV1_destroy(s ClientState, object_id ObjectID[ZxdgToplevelDecorationV1]) bool
	ZxdgToplevelDecorationV1_set_mode(s ClientState, object_id ObjectID[ZxdgToplevelDecorationV1], mode ZxdgToplevelDecorationV1Mode_enum)
	ZxdgToplevelDecorationV1_unset_mode(s ClientState, object_id ObjectID[ZxdgToplevelDecorationV1])
	OnBind(s ClientState, name AnyObjectID, interface_ string, new_id AnyObjectID, version_number uint32)
}

type ZxdgToplevelDecorationV1 struct {
	Delegate ZxdgToplevelDecorationV1_delegate
}

func (p *ZxdgToplevelDecorationV1) GetDelegate() ZxdgToplevelDecorationV1_delegate {
	return p.Delegate
}
func (p *ZxdgToplevelDecorationV1) GetBindable() OnBindable {
	return p.Delegate
}

func ZxdgToplevelDecorationV1_configure(s Sender, eventObjectID ObjectID[ZxdgToplevelDecorationV1], mode ZxdgToplevelDecorationV1Mode_enum) {
	data := make([]byte, 0)
	putUint32 := func(v uint32) { data = append(data, byte(v), byte(v>>8), byte(v>>16), byte(v>>24)) }
	var fileDescriptor *FileDescriptor
	putUint32(uint32(mode))
	obj := OutgoingEvent{
		ObjectID:       AnyObjectID(eventObjectID),
		Opcode:         0,
		Data:           data,
		FileDescriptor: fileDescriptor,
	}
	s.Send(obj)
}

func (p *ZxdgToplevelDecorationV1) OnRequest(s FileDescriptorClaimClientState, message Message) {
	_data_in_offset__ := 0
	_ = _data_in_offset__
	d := p.Delegate
	switch message.Opcode {
	case 0:
		{

			if DebugRequests {
				fmt.Print("ZxdgToplevelDecorationV1@", message.ObjectID, ".destroy(")
				fmt.Println(")")
			}

			autoRemove := d.ZxdgToplevelDecorationV1_destroy(s, ObjectID[ZxdgToplevelDecorationV1](message.ObjectID))
			if autoRemove {
				s.RemoveObject(message.ObjectID)
			}
			break
		}

	case 1:
		{

			mode := ZxdgToplevelDecorationV1Mode_enum(uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			if DebugRequests {
				fmt.Print("ZxdgToplevelDecorationV1@", message.ObjectID, ".set_mode(")
				fmt.Println("mode: ", mode, ")")
			}

			d.ZxdgToplevelDecorationV1_set_mode(s, ObjectID[ZxdgToplevelDecorationV1](message.ObjectID), mode)
			break
		}

	case 2:
		{

			if DebugRequests {
				fmt.Print("ZxdgToplevelDecorationV1@", message.ObjectID, ".unset_mode(")
				fmt.Println(")")
			}

			d.ZxdgToplevelDecorationV1_unset_mode(s, ObjectID[ZxdgToplevelDecorationV1](message.ObjectID))
			break
		}

	default:
		fmt.Println("Unknown opcode on ZxdgToplevelDecorationV1", message.Opcode)
	}
}

type ZxdgToplevelDecorationV1Error_enum uint32

const (
	ZxdgToplevelDecorationV1Error_enum_unconfigured_buffer ZxdgToplevelDecorationV1Error_enum = 0
	ZxdgToplevelDecorationV1Error_enum_already_constructed ZxdgToplevelDecorationV1Error_enum = 1
	ZxdgToplevelDecorationV1Error_enum_orphaned            ZxdgToplevelDecorationV1Error_enum = 2
	ZxdgToplevelDecorationV1Error_enum_invalid_mode        ZxdgToplevelDecorationV1Error_enum = 3
)

type ZxdgToplevelDecorationV1Mode_enum uint32

const (
	ZxdgToplevelDecorationV1Mode_enum_client_side ZxdgToplevelDecorationV1Mode_enum = 1
	ZxdgToplevelDecorationV1Mode_enum_server_side ZxdgToplevelDecorationV1Mode_enum = 2
)
