// Code generated by `cmd/protocols`; DO NOT EDIT.

package protocols

import "fmt"

type XdgWmBase_delegate interface {
	XdgWmBase_destroy(s ClientState, object_id ObjectID[XdgWmBase]) bool
	XdgWmBase_create_positioner(s ClientState, object_id ObjectID[XdgWmBase], id ObjectID[XdgPositioner])
	XdgWmBase_get_xdg_surface(s ClientState, object_id ObjectID[XdgWmBase], id ObjectID[XdgSurface], surface ObjectID[WlSurface])
	XdgWmBase_pong(s ClientState, object_id ObjectID[XdgWmBase], serial uint32)
	OnBind(s ClientState, name AnyObjectID, interface_ string, new_id AnyObjectID, version_number uint32)
}

type XdgWmBase struct {
	Delegate XdgWmBase_delegate
}

func (p *XdgWmBase) GetDelegate() XdgWmBase_delegate {
	return p.Delegate
}
func (p *XdgWmBase) GetBindable() OnBindable {
	return p.Delegate
}

func XdgWmBase_ping(s Sender, eventObjectID ObjectID[XdgWmBase], serial uint32) {
	data := make([]byte, 0)
	putUint32 := func(v uint32) { data = append(data, byte(v), byte(v>>8), byte(v>>16), byte(v>>24)) }
	var fileDescriptor *FileDescriptor
	putUint32(uint32(serial))
	obj := OutgoingEvent{
		ObjectID:       AnyObjectID(eventObjectID),
		Opcode:         0,
		Data:           data,
		FileDescriptor: fileDescriptor,
	}
	s.Send(obj)
}

func (p *XdgWmBase) OnRequest(s FileDescriptorClaimClientState, message Message) {
	_data_in_offset__ := 0
	_ = _data_in_offset__
	d := p.Delegate
	switch message.Opcode {
	case 0:
		{

			if DebugRequests {
				fmt.Print("XdgWmBase@", message.ObjectID, ".destroy(")
				fmt.Println(")")
			}

			autoRemove := d.XdgWmBase_destroy(s, ObjectID[XdgWmBase](message.ObjectID))
			if autoRemove {
				s.RemoveObject(message.ObjectID)
			}
			break
		}

	case 1:
		{

			idVal := uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24
			id := ObjectID[XdgPositioner](idVal)
			_data_in_offset__ += 4

			if DebugRequests {
				fmt.Print("XdgWmBase@", message.ObjectID, ".create_positioner(")
				fmt.Println("id: ", id, ")")
			}

			d.XdgWmBase_create_positioner(s, ObjectID[XdgWmBase](message.ObjectID), id)
			break
		}

	case 2:
		{

			idVal := uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24
			id := ObjectID[XdgSurface](idVal)
			_data_in_offset__ += 4

			surface := ObjectID[WlSurface](uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			if DebugRequests {
				fmt.Print("XdgWmBase@", message.ObjectID, ".get_xdg_surface(")
				fmt.Println("id: ", id, ", ", "surface: ", surface, ")")
			}

			d.XdgWmBase_get_xdg_surface(s, ObjectID[XdgWmBase](message.ObjectID), id, surface)
			break
		}

	case 3:
		{

			serial := uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24
			_data_in_offset__ += 4

			if DebugRequests {
				fmt.Print("XdgWmBase@", message.ObjectID, ".pong(")
				fmt.Println("serial: ", serial, ")")
			}

			d.XdgWmBase_pong(s, ObjectID[XdgWmBase](message.ObjectID), serial)
			break
		}

	default:
		fmt.Println("Unknown opcode on XdgWmBase", message.Opcode)
	}
}

type XdgWmBaseError_enum uint32

const (
	XdgWmBaseError_enum_role                  XdgWmBaseError_enum = 0
	XdgWmBaseError_enum_defunct_surfaces      XdgWmBaseError_enum = 1
	XdgWmBaseError_enum_not_the_topmost_popup XdgWmBaseError_enum = 2
	XdgWmBaseError_enum_invalid_popup_parent  XdgWmBaseError_enum = 3
	XdgWmBaseError_enum_invalid_surface_state XdgWmBaseError_enum = 4
	XdgWmBaseError_enum_invalid_positioner    XdgWmBaseError_enum = 5
	XdgWmBaseError_enum_unresponsive          XdgWmBaseError_enum = 6
)

type XdgPositioner_delegate interface {
	XdgPositioner_destroy(s ClientState, object_id ObjectID[XdgPositioner]) bool
	XdgPositioner_set_size(s ClientState, object_id ObjectID[XdgPositioner], width int32, height int32)
	XdgPositioner_set_anchor_rect(s ClientState, object_id ObjectID[XdgPositioner], x int32, y int32, width int32, height int32)
	XdgPositioner_set_anchor(s ClientState, object_id ObjectID[XdgPositioner], anchor XdgPositionerAnchor_enum)
	XdgPositioner_set_gravity(s ClientState, object_id ObjectID[XdgPositioner], gravity XdgPositionerGravity_enum)
	XdgPositioner_set_constraint_adjustment(s ClientState, object_id ObjectID[XdgPositioner], constraint_adjustment XdgPositionerConstraintAdjustment_enum)
	XdgPositioner_set_offset(s ClientState, object_id ObjectID[XdgPositioner], x int32, y int32)
	XdgPositioner_set_reactive(s ClientState, object_id ObjectID[XdgPositioner])
	XdgPositioner_set_parent_size(s ClientState, object_id ObjectID[XdgPositioner], parent_width int32, parent_height int32)
	XdgPositioner_set_parent_configure(s ClientState, object_id ObjectID[XdgPositioner], serial uint32)
	OnBind(s ClientState, name AnyObjectID, interface_ string, new_id AnyObjectID, version_number uint32)
}

type XdgPositioner struct {
	Delegate XdgPositioner_delegate
}

func (p *XdgPositioner) GetDelegate() XdgPositioner_delegate {
	return p.Delegate
}
func (p *XdgPositioner) GetBindable() OnBindable {
	return p.Delegate
}

func (p *XdgPositioner) OnRequest(s FileDescriptorClaimClientState, message Message) {
	_data_in_offset__ := 0
	_ = _data_in_offset__
	d := p.Delegate
	switch message.Opcode {
	case 0:
		{

			if DebugRequests {
				fmt.Print("XdgPositioner@", message.ObjectID, ".destroy(")
				fmt.Println(")")
			}

			autoRemove := d.XdgPositioner_destroy(s, ObjectID[XdgPositioner](message.ObjectID))
			if autoRemove {
				s.RemoveObject(message.ObjectID)
			}
			break
		}

	case 1:
		{

			width := int32(uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			height := int32(uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			if DebugRequests {
				fmt.Print("XdgPositioner@", message.ObjectID, ".set_size(")
				fmt.Println("width: ", width, ", ", "height: ", height, ")")
			}

			d.XdgPositioner_set_size(s, ObjectID[XdgPositioner](message.ObjectID), width, height)
			break
		}

	case 2:
		{

			x := int32(uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			y := int32(uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			width := int32(uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			height := int32(uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			if DebugRequests {
				fmt.Print("XdgPositioner@", message.ObjectID, ".set_anchor_rect(")
				fmt.Println("x: ", x, ", ", "y: ", y, ", ", "width: ", width, ", ", "height: ", height, ")")
			}

			d.XdgPositioner_set_anchor_rect(s, ObjectID[XdgPositioner](message.ObjectID), x, y, width, height)
			break
		}

	case 3:
		{

			anchor := XdgPositionerAnchor_enum(uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			if DebugRequests {
				fmt.Print("XdgPositioner@", message.ObjectID, ".set_anchor(")
				fmt.Println("anchor: ", anchor, ")")
			}

			d.XdgPositioner_set_anchor(s, ObjectID[XdgPositioner](message.ObjectID), anchor)
			break
		}

	case 4:
		{

			gravity := XdgPositionerGravity_enum(uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			if DebugRequests {
				fmt.Print("XdgPositioner@", message.ObjectID, ".set_gravity(")
				fmt.Println("gravity: ", gravity, ")")
			}

			d.XdgPositioner_set_gravity(s, ObjectID[XdgPositioner](message.ObjectID), gravity)
			break
		}

	case 5:
		{

			constraint_adjustment := XdgPositionerConstraintAdjustment_enum(uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			if DebugRequests {
				fmt.Print("XdgPositioner@", message.ObjectID, ".set_constraint_adjustment(")
				fmt.Println("constraint_adjustment: ", constraint_adjustment, ")")
			}

			d.XdgPositioner_set_constraint_adjustment(s, ObjectID[XdgPositioner](message.ObjectID), constraint_adjustment)
			break
		}

	case 6:
		{

			x := int32(uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			y := int32(uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			if DebugRequests {
				fmt.Print("XdgPositioner@", message.ObjectID, ".set_offset(")
				fmt.Println("x: ", x, ", ", "y: ", y, ")")
			}

			d.XdgPositioner_set_offset(s, ObjectID[XdgPositioner](message.ObjectID), x, y)
			break
		}

	case 7:
		{

			if DebugRequests {
				fmt.Print("XdgPositioner@", message.ObjectID, ".set_reactive(")
				fmt.Println(")")
			}

			d.XdgPositioner_set_reactive(s, ObjectID[XdgPositioner](message.ObjectID))
			break
		}

	case 8:
		{

			parent_width := int32(uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			parent_height := int32(uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			if DebugRequests {
				fmt.Print("XdgPositioner@", message.ObjectID, ".set_parent_size(")
				fmt.Println("parent_width: ", parent_width, ", ", "parent_height: ", parent_height, ")")
			}

			d.XdgPositioner_set_parent_size(s, ObjectID[XdgPositioner](message.ObjectID), parent_width, parent_height)
			break
		}

	case 9:
		{

			serial := uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24
			_data_in_offset__ += 4

			if DebugRequests {
				fmt.Print("XdgPositioner@", message.ObjectID, ".set_parent_configure(")
				fmt.Println("serial: ", serial, ")")
			}

			d.XdgPositioner_set_parent_configure(s, ObjectID[XdgPositioner](message.ObjectID), serial)
			break
		}

	default:
		fmt.Println("Unknown opcode on XdgPositioner", message.Opcode)
	}
}

type XdgPositionerError_enum uint32

const (
	XdgPositionerError_enum_invalid_input XdgPositionerError_enum = 0
)

type XdgPositionerAnchor_enum uint32

const (
	XdgPositionerAnchor_enum_none         XdgPositionerAnchor_enum = 0
	XdgPositionerAnchor_enum_top          XdgPositionerAnchor_enum = 1
	XdgPositionerAnchor_enum_bottom       XdgPositionerAnchor_enum = 2
	XdgPositionerAnchor_enum_left         XdgPositionerAnchor_enum = 3
	XdgPositionerAnchor_enum_right        XdgPositionerAnchor_enum = 4
	XdgPositionerAnchor_enum_top_left     XdgPositionerAnchor_enum = 5
	XdgPositionerAnchor_enum_bottom_left  XdgPositionerAnchor_enum = 6
	XdgPositionerAnchor_enum_top_right    XdgPositionerAnchor_enum = 7
	XdgPositionerAnchor_enum_bottom_right XdgPositionerAnchor_enum = 8
)

type XdgPositionerGravity_enum uint32

const (
	XdgPositionerGravity_enum_none         XdgPositionerGravity_enum = 0
	XdgPositionerGravity_enum_top          XdgPositionerGravity_enum = 1
	XdgPositionerGravity_enum_bottom       XdgPositionerGravity_enum = 2
	XdgPositionerGravity_enum_left         XdgPositionerGravity_enum = 3
	XdgPositionerGravity_enum_right        XdgPositionerGravity_enum = 4
	XdgPositionerGravity_enum_top_left     XdgPositionerGravity_enum = 5
	XdgPositionerGravity_enum_bottom_left  XdgPositionerGravity_enum = 6
	XdgPositionerGravity_enum_top_right    XdgPositionerGravity_enum = 7
	XdgPositionerGravity_enum_bottom_right XdgPositionerGravity_enum = 8
)

type XdgPositionerConstraintAdjustment_enum uint32

const (
	XdgPositionerConstraintAdjustment_enum_none     XdgPositionerConstraintAdjustment_enum = 0
	XdgPositionerConstraintAdjustment_enum_slide_x  XdgPositionerConstraintAdjustment_enum = 1
	XdgPositionerConstraintAdjustment_enum_slide_y  XdgPositionerConstraintAdjustment_enum = 2
	XdgPositionerConstraintAdjustment_enum_flip_x   XdgPositionerConstraintAdjustment_enum = 4
	XdgPositionerConstraintAdjustment_enum_flip_y   XdgPositionerConstraintAdjustment_enum = 8
	XdgPositionerConstraintAdjustment_enum_resize_x XdgPositionerConstraintAdjustment_enum = 16
	XdgPositionerConstraintAdjustment_enum_resize_y XdgPositionerConstraintAdjustment_enum = 32
)

type XdgSurface_delegate interface {
	XdgSurface_destroy(s ClientState, object_id ObjectID[XdgSurface]) bool
	XdgSurface_get_toplevel(s ClientState, object_id ObjectID[XdgSurface], id ObjectID[XdgToplevel])
	XdgSurface_get_popup(s ClientState, object_id ObjectID[XdgSurface], id ObjectID[XdgPopup], parent *ObjectID[XdgSurface], positioner ObjectID[XdgPositioner])
	XdgSurface_set_window_geometry(s ClientState, object_id ObjectID[XdgSurface], x int32, y int32, width int32, height int32)
	XdgSurface_ack_configure(s ClientState, object_id ObjectID[XdgSurface], serial uint32)
	OnBind(s ClientState, name AnyObjectID, interface_ string, new_id AnyObjectID, version_number uint32)
}

type XdgSurface struct {
	Delegate XdgSurface_delegate
}

func (p *XdgSurface) GetDelegate() XdgSurface_delegate {
	return p.Delegate
}
func (p *XdgSurface) GetBindable() OnBindable {
	return p.Delegate
}

func XdgSurface_configure(s Sender, eventObjectID ObjectID[XdgSurface], serial uint32) {
	data := make([]byte, 0)
	putUint32 := func(v uint32) { data = append(data, byte(v), byte(v>>8), byte(v>>16), byte(v>>24)) }
	var fileDescriptor *FileDescriptor
	putUint32(uint32(serial))
	obj := OutgoingEvent{
		ObjectID:       AnyObjectID(eventObjectID),
		Opcode:         0,
		Data:           data,
		FileDescriptor: fileDescriptor,
	}
	s.Send(obj)
}

func (p *XdgSurface) OnRequest(s FileDescriptorClaimClientState, message Message) {
	_data_in_offset__ := 0
	_ = _data_in_offset__
	d := p.Delegate
	switch message.Opcode {
	case 0:
		{

			if DebugRequests {
				fmt.Print("XdgSurface@", message.ObjectID, ".destroy(")
				fmt.Println(")")
			}

			autoRemove := d.XdgSurface_destroy(s, ObjectID[XdgSurface](message.ObjectID))
			if autoRemove {
				s.RemoveObject(message.ObjectID)
			}
			break
		}

	case 1:
		{

			idVal := uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24
			id := ObjectID[XdgToplevel](idVal)
			_data_in_offset__ += 4

			if DebugRequests {
				fmt.Print("XdgSurface@", message.ObjectID, ".get_toplevel(")
				fmt.Println("id: ", id, ")")
			}

			d.XdgSurface_get_toplevel(s, ObjectID[XdgSurface](message.ObjectID), id)
			break
		}

	case 2:
		{

			idVal := uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24
			id := ObjectID[XdgPopup](idVal)
			_data_in_offset__ += 4

			parentTmp := uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24
			_data_in_offset__ += 4
			var parent *ObjectID[XdgSurface]
			if parentTmp != 0 {
				tmp := ObjectID[XdgSurface](parentTmp)
				parent = &tmp
			}

			positioner := ObjectID[XdgPositioner](uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			if DebugRequests {
				fmt.Print("XdgSurface@", message.ObjectID, ".get_popup(")
				fmt.Println("id: ", id, ", ", "parent: ", parent, ", ", "positioner: ", positioner, ")")
			}

			d.XdgSurface_get_popup(s, ObjectID[XdgSurface](message.ObjectID), id, parent, positioner)
			break
		}

	case 3:
		{

			x := int32(uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			y := int32(uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			width := int32(uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			height := int32(uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			if DebugRequests {
				fmt.Print("XdgSurface@", message.ObjectID, ".set_window_geometry(")
				fmt.Println("x: ", x, ", ", "y: ", y, ", ", "width: ", width, ", ", "height: ", height, ")")
			}

			d.XdgSurface_set_window_geometry(s, ObjectID[XdgSurface](message.ObjectID), x, y, width, height)
			break
		}

	case 4:
		{

			serial := uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24
			_data_in_offset__ += 4

			if DebugRequests {
				fmt.Print("XdgSurface@", message.ObjectID, ".ack_configure(")
				fmt.Println("serial: ", serial, ")")
			}

			d.XdgSurface_ack_configure(s, ObjectID[XdgSurface](message.ObjectID), serial)
			break
		}

	default:
		fmt.Println("Unknown opcode on XdgSurface", message.Opcode)
	}
}

type XdgSurfaceError_enum uint32

const (
	XdgSurfaceError_enum_not_constructed     XdgSurfaceError_enum = 1
	XdgSurfaceError_enum_already_constructed XdgSurfaceError_enum = 2
	XdgSurfaceError_enum_unconfigured_buffer XdgSurfaceError_enum = 3
	XdgSurfaceError_enum_invalid_serial      XdgSurfaceError_enum = 4
	XdgSurfaceError_enum_invalid_size        XdgSurfaceError_enum = 5
	XdgSurfaceError_enum_defunct_role_object XdgSurfaceError_enum = 6
)

type XdgToplevel_delegate interface {
	XdgToplevel_destroy(s ClientState, object_id ObjectID[XdgToplevel]) bool
	XdgToplevel_set_parent(s ClientState, object_id ObjectID[XdgToplevel], parent *ObjectID[XdgToplevel])
	XdgToplevel_set_title(s ClientState, object_id ObjectID[XdgToplevel], title string)
	XdgToplevel_set_app_id(s ClientState, object_id ObjectID[XdgToplevel], app_id string)
	XdgToplevel_show_window_menu(s ClientState, object_id ObjectID[XdgToplevel], seat ObjectID[WlSeat], serial uint32, x int32, y int32)
	XdgToplevel_move(s ClientState, object_id ObjectID[XdgToplevel], seat ObjectID[WlSeat], serial uint32)
	XdgToplevel_resize(s ClientState, object_id ObjectID[XdgToplevel], seat ObjectID[WlSeat], serial uint32, edges XdgToplevelResizeEdge_enum)
	XdgToplevel_set_max_size(s ClientState, object_id ObjectID[XdgToplevel], width int32, height int32)
	XdgToplevel_set_min_size(s ClientState, object_id ObjectID[XdgToplevel], width int32, height int32)
	XdgToplevel_set_maximized(s ClientState, object_id ObjectID[XdgToplevel])
	XdgToplevel_unset_maximized(s ClientState, object_id ObjectID[XdgToplevel])
	XdgToplevel_set_fullscreen(s ClientState, object_id ObjectID[XdgToplevel], output *ObjectID[WlOutput])
	XdgToplevel_unset_fullscreen(s ClientState, object_id ObjectID[XdgToplevel])
	XdgToplevel_set_minimized(s ClientState, object_id ObjectID[XdgToplevel])
	OnBind(s ClientState, name AnyObjectID, interface_ string, new_id AnyObjectID, version_number uint32)
}

type XdgToplevel struct {
	Delegate XdgToplevel_delegate
}

func (p *XdgToplevel) GetDelegate() XdgToplevel_delegate {
	return p.Delegate
}
func (p *XdgToplevel) GetBindable() OnBindable {
	return p.Delegate
}

func XdgToplevel_configure(s Sender, eventObjectID ObjectID[XdgToplevel], width int32, height int32, states []byte) {
	data := make([]byte, 0)
	putUint32 := func(v uint32) { data = append(data, byte(v), byte(v>>8), byte(v>>16), byte(v>>24)) }
	putInt32 := func(v int32) { putUint32(uint32(v)) }
	var fileDescriptor *FileDescriptor
	putInt32(int32(width))
	putInt32(int32(height))
	{
		n := len(states)
		putUint32(uint32(n))
		data = append(data, states...)
		if pad := (4 - (n % 4)) % 4; pad != 0 {
			data = append(data, make([]byte, pad)...)
		}
	}
	obj := OutgoingEvent{
		ObjectID:       AnyObjectID(eventObjectID),
		Opcode:         0,
		Data:           data,
		FileDescriptor: fileDescriptor,
	}
	s.Send(obj)
}

func XdgToplevel_close(s Sender, eventObjectID ObjectID[XdgToplevel]) {
	data := make([]byte, 0)
	var fileDescriptor *FileDescriptor
	obj := OutgoingEvent{
		ObjectID:       AnyObjectID(eventObjectID),
		Opcode:         1,
		Data:           data,
		FileDescriptor: fileDescriptor,
	}
	s.Send(obj)
}

func XdgToplevel_configure_bounds(s Sender, boundVersion uint32, eventObjectID ObjectID[XdgToplevel], width int32, height int32) {
	if boundVersion < 4 {
		// Event not available in this version; skip
		return
	}
	data := make([]byte, 0)
	putInt32 := func(v int32) { uv := uint32(v); data = append(data, byte(uv), byte(uv>>8), byte(uv>>16), byte(uv>>24)) }
	var fileDescriptor *FileDescriptor
	putInt32(int32(width))
	putInt32(int32(height))
	obj := OutgoingEvent{
		ObjectID:       AnyObjectID(eventObjectID),
		Opcode:         2,
		Data:           data,
		FileDescriptor: fileDescriptor,
	}
	s.Send(obj)
}

func XdgToplevel_wm_capabilities(s Sender, boundVersion uint32, eventObjectID ObjectID[XdgToplevel], capabilities []byte) {
	if boundVersion < 5 {
		// Event not available in this version; skip
		return
	}
	data := make([]byte, 0)
	putUint32 := func(v uint32) { data = append(data, byte(v), byte(v>>8), byte(v>>16), byte(v>>24)) }
	var fileDescriptor *FileDescriptor
	{
		n := len(capabilities)
		putUint32(uint32(n))
		data = append(data, capabilities...)
		if pad := (4 - (n % 4)) % 4; pad != 0 {
			data = append(data, make([]byte, pad)...)
		}
	}
	obj := OutgoingEvent{
		ObjectID:       AnyObjectID(eventObjectID),
		Opcode:         3,
		Data:           data,
		FileDescriptor: fileDescriptor,
	}
	s.Send(obj)
}

func (p *XdgToplevel) OnRequest(s FileDescriptorClaimClientState, message Message) {
	_data_in_offset__ := 0
	_ = _data_in_offset__
	d := p.Delegate
	switch message.Opcode {
	case 0:
		{

			if DebugRequests {
				fmt.Print("XdgToplevel@", message.ObjectID, ".destroy(")
				fmt.Println(")")
			}

			autoRemove := d.XdgToplevel_destroy(s, ObjectID[XdgToplevel](message.ObjectID))
			if autoRemove {
				s.RemoveObject(message.ObjectID)
			}
			break
		}

	case 1:
		{

			parentTmp := uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24
			_data_in_offset__ += 4
			var parent *ObjectID[XdgToplevel]
			if parentTmp != 0 {
				tmp := ObjectID[XdgToplevel](parentTmp)
				parent = &tmp
			}

			if DebugRequests {
				fmt.Print("XdgToplevel@", message.ObjectID, ".set_parent(")
				fmt.Println("parent: ", parent, ")")
			}

			d.XdgToplevel_set_parent(s, ObjectID[XdgToplevel](message.ObjectID), parent)
			break
		}

	case 2:
		{

			titleLen := int(uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4
			title := string(message.Data[_data_in_offset__ : _data_in_offset__+titleLen-1]) // NUL-terminated
			// 4-byte alignment
			if titleLen%4 != 0 {
				_data_in_offset__ += titleLen + (4 - (titleLen % 4))
			} else {
				_data_in_offset__ += titleLen
			}

			if DebugRequests {
				fmt.Print("XdgToplevel@", message.ObjectID, ".set_title(")
				fmt.Println("title: ", title, ")")
			}

			d.XdgToplevel_set_title(s, ObjectID[XdgToplevel](message.ObjectID), title)
			break
		}

	case 3:
		{

			app_idLen := int(uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4
			app_id := string(message.Data[_data_in_offset__ : _data_in_offset__+app_idLen-1]) // NUL-terminated
			// 4-byte alignment
			if app_idLen%4 != 0 {
				_data_in_offset__ += app_idLen + (4 - (app_idLen % 4))
			} else {
				_data_in_offset__ += app_idLen
			}

			if DebugRequests {
				fmt.Print("XdgToplevel@", message.ObjectID, ".set_app_id(")
				fmt.Println("app_id: ", app_id, ")")
			}

			d.XdgToplevel_set_app_id(s, ObjectID[XdgToplevel](message.ObjectID), app_id)
			break
		}

	case 4:
		{

			seat := ObjectID[WlSeat](uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			serial := uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24
			_data_in_offset__ += 4

			x := int32(uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			y := int32(uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			if DebugRequests {
				fmt.Print("XdgToplevel@", message.ObjectID, ".show_window_menu(")
				fmt.Println("seat: ", seat, ", ", "serial: ", serial, ", ", "x: ", x, ", ", "y: ", y, ")")
			}

			d.XdgToplevel_show_window_menu(s, ObjectID[XdgToplevel](message.ObjectID), seat, serial, x, y)
			break
		}

	case 5:
		{

			seat := ObjectID[WlSeat](uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			serial := uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24
			_data_in_offset__ += 4

			if DebugRequests {
				fmt.Print("XdgToplevel@", message.ObjectID, ".move(")
				fmt.Println("seat: ", seat, ", ", "serial: ", serial, ")")
			}

			d.XdgToplevel_move(s, ObjectID[XdgToplevel](message.ObjectID), seat, serial)
			break
		}

	case 6:
		{

			seat := ObjectID[WlSeat](uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			serial := uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24
			_data_in_offset__ += 4

			edges := XdgToplevelResizeEdge_enum(uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			if DebugRequests {
				fmt.Print("XdgToplevel@", message.ObjectID, ".resize(")
				fmt.Println("seat: ", seat, ", ", "serial: ", serial, ", ", "edges: ", edges, ")")
			}

			d.XdgToplevel_resize(s, ObjectID[XdgToplevel](message.ObjectID), seat, serial, edges)
			break
		}

	case 7:
		{

			width := int32(uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			height := int32(uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			if DebugRequests {
				fmt.Print("XdgToplevel@", message.ObjectID, ".set_max_size(")
				fmt.Println("width: ", width, ", ", "height: ", height, ")")
			}

			d.XdgToplevel_set_max_size(s, ObjectID[XdgToplevel](message.ObjectID), width, height)
			break
		}

	case 8:
		{

			width := int32(uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			height := int32(uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			if DebugRequests {
				fmt.Print("XdgToplevel@", message.ObjectID, ".set_min_size(")
				fmt.Println("width: ", width, ", ", "height: ", height, ")")
			}

			d.XdgToplevel_set_min_size(s, ObjectID[XdgToplevel](message.ObjectID), width, height)
			break
		}

	case 9:
		{

			if DebugRequests {
				fmt.Print("XdgToplevel@", message.ObjectID, ".set_maximized(")
				fmt.Println(")")
			}

			d.XdgToplevel_set_maximized(s, ObjectID[XdgToplevel](message.ObjectID))
			break
		}

	case 10:
		{

			if DebugRequests {
				fmt.Print("XdgToplevel@", message.ObjectID, ".unset_maximized(")
				fmt.Println(")")
			}

			d.XdgToplevel_unset_maximized(s, ObjectID[XdgToplevel](message.ObjectID))
			break
		}

	case 11:
		{

			outputTmp := uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24
			_data_in_offset__ += 4
			var output *ObjectID[WlOutput]
			if outputTmp != 0 {
				tmp := ObjectID[WlOutput](outputTmp)
				output = &tmp
			}

			if DebugRequests {
				fmt.Print("XdgToplevel@", message.ObjectID, ".set_fullscreen(")
				fmt.Println("output: ", output, ")")
			}

			d.XdgToplevel_set_fullscreen(s, ObjectID[XdgToplevel](message.ObjectID), output)
			break
		}

	case 12:
		{

			if DebugRequests {
				fmt.Print("XdgToplevel@", message.ObjectID, ".unset_fullscreen(")
				fmt.Println(")")
			}

			d.XdgToplevel_unset_fullscreen(s, ObjectID[XdgToplevel](message.ObjectID))
			break
		}

	case 13:
		{

			if DebugRequests {
				fmt.Print("XdgToplevel@", message.ObjectID, ".set_minimized(")
				fmt.Println(")")
			}

			d.XdgToplevel_set_minimized(s, ObjectID[XdgToplevel](message.ObjectID))
			break
		}

	default:
		fmt.Println("Unknown opcode on XdgToplevel", message.Opcode)
	}
}

type XdgToplevelError_enum uint32

const (
	XdgToplevelError_enum_invalid_resize_edge XdgToplevelError_enum = 0
	XdgToplevelError_enum_invalid_parent      XdgToplevelError_enum = 1
	XdgToplevelError_enum_invalid_size        XdgToplevelError_enum = 2
)

type XdgToplevelResizeEdge_enum uint32

const (
	XdgToplevelResizeEdge_enum_none         XdgToplevelResizeEdge_enum = 0
	XdgToplevelResizeEdge_enum_top          XdgToplevelResizeEdge_enum = 1
	XdgToplevelResizeEdge_enum_bottom       XdgToplevelResizeEdge_enum = 2
	XdgToplevelResizeEdge_enum_left         XdgToplevelResizeEdge_enum = 4
	XdgToplevelResizeEdge_enum_top_left     XdgToplevelResizeEdge_enum = 5
	XdgToplevelResizeEdge_enum_bottom_left  XdgToplevelResizeEdge_enum = 6
	XdgToplevelResizeEdge_enum_right        XdgToplevelResizeEdge_enum = 8
	XdgToplevelResizeEdge_enum_top_right    XdgToplevelResizeEdge_enum = 9
	XdgToplevelResizeEdge_enum_bottom_right XdgToplevelResizeEdge_enum = 10
)

type XdgToplevelState_enum uint32

const (
	XdgToplevelState_enum_maximized    XdgToplevelState_enum = 1
	XdgToplevelState_enum_fullscreen   XdgToplevelState_enum = 2
	XdgToplevelState_enum_resizing     XdgToplevelState_enum = 3
	XdgToplevelState_enum_activated    XdgToplevelState_enum = 4
	XdgToplevelState_enum_tiled_left   XdgToplevelState_enum = 5
	XdgToplevelState_enum_tiled_right  XdgToplevelState_enum = 6
	XdgToplevelState_enum_tiled_top    XdgToplevelState_enum = 7
	XdgToplevelState_enum_tiled_bottom XdgToplevelState_enum = 8
	XdgToplevelState_enum_suspended    XdgToplevelState_enum = 9
)

type XdgToplevelWmCapabilities_enum uint32

const (
	XdgToplevelWmCapabilities_enum_window_menu XdgToplevelWmCapabilities_enum = 1
	XdgToplevelWmCapabilities_enum_maximize    XdgToplevelWmCapabilities_enum = 2
	XdgToplevelWmCapabilities_enum_fullscreen  XdgToplevelWmCapabilities_enum = 3
	XdgToplevelWmCapabilities_enum_minimize    XdgToplevelWmCapabilities_enum = 4
)

type XdgPopup_delegate interface {
	XdgPopup_destroy(s ClientState, object_id ObjectID[XdgPopup]) bool
	XdgPopup_grab(s ClientState, object_id ObjectID[XdgPopup], seat ObjectID[WlSeat], serial uint32)
	XdgPopup_reposition(s ClientState, object_id ObjectID[XdgPopup], positioner ObjectID[XdgPositioner], token uint32)
	OnBind(s ClientState, name AnyObjectID, interface_ string, new_id AnyObjectID, version_number uint32)
}

type XdgPopup struct {
	Delegate XdgPopup_delegate
}

func (p *XdgPopup) GetDelegate() XdgPopup_delegate {
	return p.Delegate
}
func (p *XdgPopup) GetBindable() OnBindable {
	return p.Delegate
}

func XdgPopup_configure(s Sender, eventObjectID ObjectID[XdgPopup], x int32, y int32, width int32, height int32) {
	data := make([]byte, 0)
	putInt32 := func(v int32) { uv := uint32(v); data = append(data, byte(uv), byte(uv>>8), byte(uv>>16), byte(uv>>24)) }
	var fileDescriptor *FileDescriptor
	putInt32(int32(x))
	putInt32(int32(y))
	putInt32(int32(width))
	putInt32(int32(height))
	obj := OutgoingEvent{
		ObjectID:       AnyObjectID(eventObjectID),
		Opcode:         0,
		Data:           data,
		FileDescriptor: fileDescriptor,
	}
	s.Send(obj)
}

func XdgPopup_popup_done(s Sender, eventObjectID ObjectID[XdgPopup]) {
	data := make([]byte, 0)
	var fileDescriptor *FileDescriptor
	obj := OutgoingEvent{
		ObjectID:       AnyObjectID(eventObjectID),
		Opcode:         1,
		Data:           data,
		FileDescriptor: fileDescriptor,
	}
	s.Send(obj)
}

func XdgPopup_repositioned(s Sender, boundVersion uint32, eventObjectID ObjectID[XdgPopup], token uint32) {
	if boundVersion < 3 {
		// Event not available in this version; skip
		return
	}
	data := make([]byte, 0)
	putUint32 := func(v uint32) { data = append(data, byte(v), byte(v>>8), byte(v>>16), byte(v>>24)) }
	var fileDescriptor *FileDescriptor
	putUint32(uint32(token))
	obj := OutgoingEvent{
		ObjectID:       AnyObjectID(eventObjectID),
		Opcode:         2,
		Data:           data,
		FileDescriptor: fileDescriptor,
	}
	s.Send(obj)
}

func (p *XdgPopup) OnRequest(s FileDescriptorClaimClientState, message Message) {
	_data_in_offset__ := 0
	_ = _data_in_offset__
	d := p.Delegate
	switch message.Opcode {
	case 0:
		{

			if DebugRequests {
				fmt.Print("XdgPopup@", message.ObjectID, ".destroy(")
				fmt.Println(")")
			}

			autoRemove := d.XdgPopup_destroy(s, ObjectID[XdgPopup](message.ObjectID))
			if autoRemove {
				s.RemoveObject(message.ObjectID)
			}
			break
		}

	case 1:
		{

			seat := ObjectID[WlSeat](uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			serial := uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24
			_data_in_offset__ += 4

			if DebugRequests {
				fmt.Print("XdgPopup@", message.ObjectID, ".grab(")
				fmt.Println("seat: ", seat, ", ", "serial: ", serial, ")")
			}

			d.XdgPopup_grab(s, ObjectID[XdgPopup](message.ObjectID), seat, serial)
			break
		}

	case 2:
		{

			positioner := ObjectID[XdgPositioner](uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			token := uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24
			_data_in_offset__ += 4

			if DebugRequests {
				fmt.Print("XdgPopup@", message.ObjectID, ".reposition(")
				fmt.Println("positioner: ", positioner, ", ", "token: ", token, ")")
			}

			d.XdgPopup_reposition(s, ObjectID[XdgPopup](message.ObjectID), positioner, token)
			break
		}

	default:
		fmt.Println("Unknown opcode on XdgPopup", message.Opcode)
	}
}

type XdgPopupError_enum uint32

const (
	XdgPopupError_enum_invalid_grab XdgPopupError_enum = 0
)
