// Code generated by `cmd/protocols`; DO NOT EDIT.

package protocols

import "fmt"

type XwaylandShellV1_delegate interface {
	XwaylandShellV1_destroy(s ClientState, object_id ObjectID[XwaylandShellV1]) bool
	XwaylandShellV1_get_xwayland_surface(s ClientState, object_id ObjectID[XwaylandShellV1], id ObjectID[XwaylandSurfaceV1], surface ObjectID[WlSurface])
	OnBind(s ClientState, name AnyObjectID, interface_ string, new_id AnyObjectID, version_number uint32)
}

type XwaylandShellV1 struct {
	Delegate XwaylandShellV1_delegate
}

func (p *XwaylandShellV1) GetDelegate() XwaylandShellV1_delegate {
	return p.Delegate
}
func (p *XwaylandShellV1) GetBindable() OnBindable {
	return p.Delegate
}

func (p *XwaylandShellV1) OnRequest(s FileDescriptorClaimClientState, message Message) {
	_data_in_offset__ := 0
	_ = _data_in_offset__
	d := p.Delegate
	switch message.Opcode {
	case 0:
		{

			if DebugRequests {
				fmt.Print("XwaylandShellV1@", message.ObjectID, ".destroy(")
				fmt.Println(")")
			}

			autoRemove := d.XwaylandShellV1_destroy(s, ObjectID[XwaylandShellV1](message.ObjectID))
			if autoRemove {
				s.RemoveObject(message.ObjectID)
			}
			break
		}

	case 1:
		{

			idVal := uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24
			id := ObjectID[XwaylandSurfaceV1](idVal)
			_data_in_offset__ += 4

			surface := ObjectID[WlSurface](uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			if DebugRequests {
				fmt.Print("XwaylandShellV1@", message.ObjectID, ".get_xwayland_surface(")
				fmt.Println("id: ", id, ", ", "surface: ", surface, ")")
			}

			d.XwaylandShellV1_get_xwayland_surface(s, ObjectID[XwaylandShellV1](message.ObjectID), id, surface)
			break
		}

	default:
		fmt.Println("Unknown opcode on XwaylandShellV1", message.Opcode)
	}
}

type XwaylandShellV1Error_enum uint32

const (
	XwaylandShellV1Error_enum_role XwaylandShellV1Error_enum = 0
)

type XwaylandSurfaceV1_delegate interface {
	XwaylandSurfaceV1_set_serial(s ClientState, object_id ObjectID[XwaylandSurfaceV1], serial_lo uint32, serial_hi uint32)
	XwaylandSurfaceV1_destroy(s ClientState, object_id ObjectID[XwaylandSurfaceV1]) bool
	OnBind(s ClientState, name AnyObjectID, interface_ string, new_id AnyObjectID, version_number uint32)
}

type XwaylandSurfaceV1 struct {
	Delegate XwaylandSurfaceV1_delegate
}

func (p *XwaylandSurfaceV1) GetDelegate() XwaylandSurfaceV1_delegate {
	return p.Delegate
}
func (p *XwaylandSurfaceV1) GetBindable() OnBindable {
	return p.Delegate
}

func (p *XwaylandSurfaceV1) OnRequest(s FileDescriptorClaimClientState, message Message) {
	_data_in_offset__ := 0
	_ = _data_in_offset__
	d := p.Delegate
	switch message.Opcode {
	case 0:
		{

			serial_lo := uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24
			_data_in_offset__ += 4

			serial_hi := uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24
			_data_in_offset__ += 4

			if DebugRequests {
				fmt.Print("XwaylandSurfaceV1@", message.ObjectID, ".set_serial(")
				fmt.Println("serial_lo: ", serial_lo, ", ", "serial_hi: ", serial_hi, ")")
			}

			d.XwaylandSurfaceV1_set_serial(s, ObjectID[XwaylandSurfaceV1](message.ObjectID), serial_lo, serial_hi)
			break
		}

	case 1:
		{

			if DebugRequests {
				fmt.Print("XwaylandSurfaceV1@", message.ObjectID, ".destroy(")
				fmt.Println(")")
			}

			autoRemove := d.XwaylandSurfaceV1_destroy(s, ObjectID[XwaylandSurfaceV1](message.ObjectID))
			if autoRemove {
				s.RemoveObject(message.ObjectID)
			}
			break
		}

	default:
		fmt.Println("Unknown opcode on XwaylandSurfaceV1", message.Opcode)
	}
}

type XwaylandSurfaceV1Error_enum uint32

const (
	XwaylandSurfaceV1Error_enum_already_associated XwaylandSurfaceV1Error_enum = 0
	XwaylandSurfaceV1Error_enum_invalid_serial     XwaylandSurfaceV1Error_enum = 1
)
