// Code generated by `cmd/protocols`; DO NOT EDIT.

package protocols

import "fmt"

type ZwpXwaylandKeyboardGrabManagerV1_delegate interface {
	ZwpXwaylandKeyboardGrabManagerV1_destroy(s ClientState, object_id ObjectID[ZwpXwaylandKeyboardGrabManagerV1]) bool
	ZwpXwaylandKeyboardGrabManagerV1_grab_keyboard(s ClientState, object_id ObjectID[ZwpXwaylandKeyboardGrabManagerV1], id ObjectID[ZwpXwaylandKeyboardGrabV1], surface ObjectID[WlSurface], seat ObjectID[WlSeat])
	OnBind(s ClientState, name AnyObjectID, interface_ string, new_id AnyObjectID, version_number uint32)
}

type ZwpXwaylandKeyboardGrabManagerV1 struct {
	Delegate ZwpXwaylandKeyboardGrabManagerV1_delegate
}

func (p *ZwpXwaylandKeyboardGrabManagerV1) GetDelegate() ZwpXwaylandKeyboardGrabManagerV1_delegate {
	return p.Delegate
}
func (p *ZwpXwaylandKeyboardGrabManagerV1) GetBindable() OnBindable {
	return p.Delegate
}

func (p *ZwpXwaylandKeyboardGrabManagerV1) OnRequest(s FileDescriptorClaimClientState, message Message) {
	_data_in_offset__ := 0
	_ = _data_in_offset__
	d := p.Delegate
	switch message.Opcode {
	case 0:
		{

			if DebugRequests {
				fmt.Print("ZwpXwaylandKeyboardGrabManagerV1@", message.ObjectID, ".destroy(")
				fmt.Println(")")
			}

			autoRemove := d.ZwpXwaylandKeyboardGrabManagerV1_destroy(s, ObjectID[ZwpXwaylandKeyboardGrabManagerV1](message.ObjectID))
			if autoRemove {
				s.RemoveObject(message.ObjectID)
			}
			break
		}

	case 1:
		{

			idVal := uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24
			id := ObjectID[ZwpXwaylandKeyboardGrabV1](idVal)
			_data_in_offset__ += 4

			surface := ObjectID[WlSurface](uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			seat := ObjectID[WlSeat](uint32(message.Data[_data_in_offset__+0]) | uint32(message.Data[_data_in_offset__+1])<<8 |
				uint32(message.Data[_data_in_offset__+2])<<16 | uint32(message.Data[_data_in_offset__+3])<<24)
			_data_in_offset__ += 4

			if DebugRequests {
				fmt.Print("ZwpXwaylandKeyboardGrabManagerV1@", message.ObjectID, ".grab_keyboard(")
				fmt.Println("id: ", id, ", ", "surface: ", surface, ", ", "seat: ", seat, ")")
			}

			d.ZwpXwaylandKeyboardGrabManagerV1_grab_keyboard(s, ObjectID[ZwpXwaylandKeyboardGrabManagerV1](message.ObjectID), id, surface, seat)
			break
		}

	default:
		fmt.Println("Unknown opcode on ZwpXwaylandKeyboardGrabManagerV1", message.Opcode)
	}
}

type ZwpXwaylandKeyboardGrabV1_delegate interface {
	ZwpXwaylandKeyboardGrabV1_destroy(s ClientState, object_id ObjectID[ZwpXwaylandKeyboardGrabV1]) bool
	OnBind(s ClientState, name AnyObjectID, interface_ string, new_id AnyObjectID, version_number uint32)
}

type ZwpXwaylandKeyboardGrabV1 struct {
	Delegate ZwpXwaylandKeyboardGrabV1_delegate
}

func (p *ZwpXwaylandKeyboardGrabV1) GetDelegate() ZwpXwaylandKeyboardGrabV1_delegate {
	return p.Delegate
}
func (p *ZwpXwaylandKeyboardGrabV1) GetBindable() OnBindable {
	return p.Delegate
}

func (p *ZwpXwaylandKeyboardGrabV1) OnRequest(s FileDescriptorClaimClientState, message Message) {
	_data_in_offset__ := 0
	_ = _data_in_offset__
	d := p.Delegate
	switch message.Opcode {
	case 0:
		{

			if DebugRequests {
				fmt.Print("ZwpXwaylandKeyboardGrabV1@", message.ObjectID, ".destroy(")
				fmt.Println(")")
			}

			autoRemove := d.ZwpXwaylandKeyboardGrabV1_destroy(s, ObjectID[ZwpXwaylandKeyboardGrabV1](message.ObjectID))
			if autoRemove {
				s.RemoveObject(message.ObjectID)
			}
			break
		}

	default:
		fmt.Println("Unknown opcode on ZwpXwaylandKeyboardGrabV1", message.Opcode)
	}
}
